#!/bin/bash

echo "Executing Brewfile..."

# Check for Homebrew and install if we don't have it
if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Install Rosetta
sudo softwareupdate --install-rosetta

brew install --cask alfred
brew install --cask bitwarden
brew install --cask docker
brew install --cask firefox
brew install --cask goland
brew install --cask google-chrome
brew install --cask insomnia
brew install --cask iterm2
brew install --cask microsoft-teams
brew install --cask protonvpn
brew install --cask rectangle
brew install --cask robo-3t
brew install --cask signal
brew install --cask slack
brew install --cask spotify
brew install --cask thunderbird
brew install --cask ubersicht
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask webstorm

brew install node@18  # current LTS version
brew link --overwrite node@18

brew install koekeishiya/formulae/skhd
brew services start skhd
brew install koekeishiya/formulae/yabai
brew services start yabai
brew install neovim
brew install yarn

# Mongo
brew tap mongodb/brew
brew install mongodb-community@4.2
brew services start mongodb/brew/mongodb-community@4.2

brew cleanup
